/* Source: MOD POC OVER 5G PULSE NETWORK 02-10-2026.pdf, page 14.
   The source schedule is Sep–Nov 2025; its reference marker is 30 Sep 2025.
   Bar extents follow the raster source, not approved task dates or durations. */
(()=>{'use strict';
window.MOD_IMPLEMENTATION_CONTENT={
 dates:[['28','SEP',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_0_2_001"] ?? 'سبتمبر')],['05','OCT',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_1_2_002"] ?? 'أكتوبر')],['12','OCT',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_2_2_003"] ?? 'أكتوبر')],['19','OCT',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_3_2_004"] ?? 'أكتوبر')],['26','OCT',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_4_2_005"] ?? 'أكتوبر')],['02','NOV',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_5_2_006"] ?? 'نوفمبر')],['09','NOV',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_6_2_007"] ?? 'نوفمبر')],['11','NOV',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_dates_7_2_008"] ?? 'نوفمبر')]],
 workstreams:[
  {id:'shelter',icon:'container',name:{en:'DC on the Wheel',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_name_ar_009"] ?? 'مركز البيانات المتنقل')},place:{en:'Mahawi Camp',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_place_ar_010"] ?? 'معسكر محوي')},focus:{en:'Mobile data-centre shelter',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_focus_ar_011"] ?? 'مأوى مركز البيانات المتنقل')},description:{en:'A transportable data-centre shelter: equipment racks, power distribution, cooling and the physical hand-off to Pulse.',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_description_ar_012"] ?? 'مأوى متنقل لمركز البيانات: خزائن تجهيزات وتوزيع للطاقة وتبريد ونقطة ربط مادية مع شبكة Pulse.')},chips:{en:['Shelter mobilisation','Power + cooling','Pulse connectivity'],ar:[(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_chips_ar_0_013"] ?? 'نقل المأوى'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_chips_ar_1_014"] ?? 'الطاقة والتبريد'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_chips_ar_2_015"] ?? 'الربط مع Pulse')]},tasks:[
   ['01.01','Customer Access Approval',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_tasks_0_2_016"] ?? 'موافقة العميل على الدخول'),.08,.42],
   ['01.02','Site Survey',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_tasks_1_2_017"] ?? 'المسح الميداني'),.46,.50],
   ['01.03','Shift DC Shelter to Mahawi Camp',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_tasks_2_2_018"] ?? 'نقل مأوى مركز البيانات إلى معسكر محوي'),.94,.50],
   ['01.04','DC installation, power up and connectivity',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_tasks_3_2_019"] ?? 'تركيب مركز البيانات وتشغيل الطاقة والاتصال'),1.41,.76],
   ['01.05','Link Establishment between Pulse Core and Mahawi camp',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_tasks_4_2_020"] ?? 'إنشاء الربط بين شبكة Pulse الأساسية ومعسكر محوي'),1.42,.76],
   ['01.06','Integration with Pulse core',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_0_tasks_5_2_021"] ?? 'التكامل مع شبكة Pulse الأساسية'),2.19,.69]]},
  {id:'core',icon:'server',name:{en:'Mobile Core',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_name_ar_022"] ?? 'الشبكة الأساسية المتنقلة')},place:{en:'Re-configuration',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_place_ar_023"] ?? 'إعادة التهيئة')},focus:{en:'Pulse core configuration',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_focus_ar_024"] ?? 'تهيئة شبكة Pulse الأساسية')},description:{en:'A cutaway view into the rack environment. Explore the approvals, customer PLMN confirmation and licence configuration in the reference plan.',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_description_ar_025"] ?? 'منظور داخلي لخزائن التجهيزات. استعرض الموافقات وتأكيد العميل لمعرّف PLMN وتجديد الترخيص والتهيئة في الخطة المرجعية.')},chips:{en:['DC access','PLMN confirmation','Licence + configuration'],ar:[(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_chips_ar_0_026"] ?? 'دخول مركز البيانات'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_chips_ar_1_027"] ?? 'تأكيد PLMN'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_chips_ar_2_028"] ?? 'الترخيص والتهيئة')]},tasks:[
   ['02.01','DC Access Approval',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_tasks_0_2_029"] ?? 'موافقة الدخول إلى مركز البيانات'),.16,.58],
   ['02.02','PLMN ID confirmation by customer',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_tasks_1_2_030"] ?? 'تأكيد العميل لمعرّف PLMN'),.67,.85],
   ['02.03','License renewal and configuration',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_1_tasks_2_2_031"] ?? 'تجديد الترخيص والتهيئة'),1.64,.63]]},
  {id:'ran',icon:'radio-tower',name:{en:'RAN Deployment',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_name_ar_032"] ?? 'نشر شبكة النفاذ الراديوي')},place:{en:'From survey to drive test',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_place_ar_033"] ?? 'من المسح إلى اختبار القيادة')},focus:{en:'Radio access deployment',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_focus_ar_034"] ?? 'نشر شبكة النفاذ الراديوي')},description:{en:'A detailed radio site, built around sector antennas, remote radio units, cable routes, equipment cabinets and the site power interface.',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_description_ar_035"] ?? 'موقع راديو مفصّل يضم هوائيات قطاعية ووحدات راديو ومسارات كابلات وخزائن تجهيزات وواجهة طاقة الموقع.')},chips:{en:['Civil + power','RAN + transmission','Integration + drive test'],ar:[(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_chips_ar_0_036"] ?? 'الأعمال المدنية والطاقة'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_chips_ar_1_037"] ?? 'الراديو والنقل'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_chips_ar_2_038"] ?? 'التكامل واختبار القيادة')]},tasks:[
   ['03.01','Access Approval (Customer Premises)',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_0_2_039"] ?? 'موافقة الدخول إلى موقع العميل'),.15,.66],
   ['03.02','Site Survey',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_1_2_040"] ?? 'المسح الميداني'),.78,.63],
   ['03.03','Prepare BOQ & Required Materials',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_2_2_041"] ?? 'إعداد جدول الكميات والمواد المطلوبة'),1.40,.68],
   ['03.04','Release HW',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_3_2_042"] ?? 'صرف الأجهزة'),2.11,.78],
   ['03.05','Civil & Power Arrangement',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_4_2_043"] ?? 'تجهيز الأعمال المدنية والطاقة'),2.87,.97],
   ['03.06','RAN Installation',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_5_2_044"] ?? 'تركيب شبكة النفاذ الراديوي'),3.81,1.59],
   ['03.07','Link Provisioning',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_6_2_045"] ?? 'توفير الربط'),2.21,3.20,5.59,.49],
   ['03.08','Commissioning & Integration',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_7_2_046"] ?? 'التشغيل والتكامل'),6.32,.52],
   ['03.09','Drive Test',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_2_tasks_8_2_047"] ?? 'اختبار القيادة'),6.97,.48]]},
  {id:'demonstration',icon:'monitor-smartphone',name:{en:'UCs Integration',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_name_ar_048"] ?? 'تكامل حالات الاستخدام')},place:{en:'and Demonstration',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_place_ar_049"] ?? 'والعرض التوضيحي')},focus:{en:'Devices and demonstration',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_focus_ar_050"] ?? 'الأجهزة والعرض التوضيحي')},description:{en:'Devices and the GINA command view brought together over the conceptual Pulse 5G service path, ready for integration testing and demonstration.',ar:(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_description_ar_051"] ?? 'تجتمع الأجهزة وواجهة القيادة GINA عبر مسار خدمات Pulse 5G التصوّري استعداداً لاختبار التكامل والعرض.')},chips:{en:['Device integration','Initial testing','Customer demonstration'],ar:[(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_chips_ar_0_052"] ?? 'تكامل الأجهزة'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_chips_ar_1_053"] ?? 'الاختبار الأولي'),(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_chips_ar_2_054"] ?? 'العرض للعميل')]},tasks:[
   ['04.01','Devices Integration and initial testing',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_tasks_0_2_055"] ?? 'تكامل الأجهزة والاختبار الأولي'),5.56,.59],
   ['04.02','Customer Demonstration',(globalThis.MOD_AR_TEXT?.["14-implementation-plan"]?.["implementation_window_MOD_IMPLEMENTATION_CONTENT_workstreams_3_tasks_1_2_056"] ?? 'العرض التوضيحي للعميل'),6.10,1.79]]}
 ]};
})();
