/* Presenter controls for the original animated deployment scene. Copy is external. */
(()=>{
 const host=document.getElementById('approachSlide');let state={index:-1,lang:'en',motion:true},builtLang=null,selected=0,sequence=null;
 const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const clock={elapsed:0};const copy=()=>MOD_COPY[state.lang].approach;
 function build(){const t=copy();builtLang=state.lang;host.setAttribute('aria-label',t.title);host.innerHTML=`<header class="approach-heading"><p class="eyebrow">${esc(t.eyebrow)}</p><h1>${esc(t.title)}</h1><p class="approach-subtitle">${esc(t.subtitle)}</p></header><div class="stage-backdrop" aria-hidden="true">${MOD_CONFIG.stageImages.map((src,i)=>`<div class="stage-backdrop-frame" data-frame="${i}"><span class="paired day" style="background-image:url('${src}')"></span><span class="paired night" style="background-image:url('${src}')"></span></div>`).join('')}</div><figure class="deployment-photo">${MOD_CONFIG.stageImages.map((src,i)=>`<div class="hero-frame" data-frame="${i}"><span class="paired day" style="background-image:url('${src}')"></span><span class="paired night" style="background-image:url('${src}')"></span></div>`).join('')}<figcaption><span class="photo-status"></span><span class="hero-caption"></span></figcaption></figure><div class="core-summary"><div><small>${esc(t.core1)}</small><strong>${esc(t.pulseCore)}</strong><span>${esc(t.voice)}</span><b>${esc(t.pulseLocation)}</b></div><div><small>${esc(t.core2)}</small><strong>${esc(t.customerCore)}</strong><span>${esc(t.other)}</span><b>${esc(t.customerLocation)}</b></div></div><div class="approach-steps" role="group" aria-label="${esc(t.stepLabel)}"><span class="implementation-label">${esc(t.implementation)}</span>${t.stages.map((s,i)=>`<button class="approach-step" data-step="${i}" aria-pressed="false"><span class="card-art" aria-hidden="true"><span class="paired day" style="background-image:url('${MOD_CONFIG.stageImages[i]}')"></span><span class="paired night" style="background-image:url('${MOD_CONFIG.stageImages[i]}')"></span><span class="step-icon"><i data-lucide="${['truck','cable','radio-tower','monitor-play'][i]}"></i></span><span class="step-number" dir="ltr">0${i+1}</span></span><span class="step-copy"><strong>${esc(s.title)}</strong><span>${esc(s.detail)}</span></span><span class="step-timer"></span></button>`).join('')}<button class="sequence-replay" title="${esc(t.replay)}" aria-label="${esc(t.replay)}"><i data-lucide="rotate-ccw"></i><span>${esc(t.replay)}</span></button></div><div class="approach-scope"><strong>${esc(t.diagramTitle)}</strong><small>${esc(t.diagramNote)}</small></div><div class="approach-focus" aria-live="polite"><span class="focus-index" dir="ltr"></span><div><h2></h2><p></p></div><div class="demo-strip">${t.categories.map(n=>`<span>${esc(n)}</span>`).join('')}</div></div>`;host.querySelectorAll('[data-step]').forEach(b=>b.onclick=()=>{sequence?.kill();sequence=null;select(+b.dataset.step,true)});host.querySelector('.sequence-replay').onclick=replay;lucide.createIcons({attrs:{'aria-hidden':'true'}});select(selected,false)}
 function select(i,animate=true){selected=i;host.dataset.phase=i;host.querySelectorAll('[data-frame]').forEach(f=>f.classList.toggle('current',+f.dataset.frame===i));const t=copy();host.querySelector('.hero-caption').textContent=t.stages[i].focus;host.querySelectorAll('[data-step]').forEach((b,n)=>{b.classList.toggle('active',n===i);b.classList.toggle('visited',n<i);b.setAttribute('aria-pressed',String(n===i))});host.querySelector('.focus-index').textContent='0'+(i+1);host.querySelector('.approach-focus h2').textContent=t.stages[i].focus;host.querySelector('.approach-focus p').textContent=t.stages[i].note;if(animate||MOD_CINEMATIC.diagnostics().stage!==i)MOD_CINEMATIC.selectStage(i,animate);if(animate&&state.motion)gsap.fromTo(host.querySelector('.approach-focus'),{opacity:.2,y:10},{opacity:1,y:0,duration:.55,overwrite:true})}
 function replay(){sequence?.kill();clock.elapsed=0;select(0,true);sequence=gsap.to(clock,{elapsed:4,duration:MOD_CONFIG.approach.stageSeconds*4,ease:'none',onUpdate(){const i=Math.min(3,Math.floor(clock.elapsed));if(i!==selected)select(i,true);host.style.setProperty('--stage-progress',((clock.elapsed%1)*100)+'%')},onComplete(){host.style.setProperty('--stage-progress','100%')}});lifecycle()}
 function lifecycle(){const run=state.index===1&&state.motion&&!document.hidden;host.classList.toggle('approach-paused',!run);if(run)sequence?.resume();else sequence?.pause()}
 window.MOD_APPROACH={sync(s){const entered=s.index===1&&state.index!==1;state={...s};if(state.index===1){if(builtLang!==state.lang)build();if(entered)replay()}lifecycle()},replay,diagnostics:()=>({stage:selected,active:state.index===1,playing:!!sequence?.isActive(),language:builtLang})};document.addEventListener('visibilitychange',lifecycle);
})();
