/* Accessible final slide; the image and live type remain usable without WebGL. */
(()=>{'use strict';
 const host=document.getElementById('closingSlide'),$=s=>host.querySelector(s),COPY={en:{eyebrow:'MOD PoC OVER 5G PULSE NETWORK',title:'Thank you',subtitle:'Critical 5G sites over Pulse',overview:'Explore the use cases',restart:'Restart presentation',replay:'Replay closing',scene:'Illustrative 5G environment',fallback:'The closing illustration remains available. The interactive 3D view could not be loaded.'},ar:{eyebrow:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_eyebrow_001"] ?? 'إثبات المفهوم لوزارة الدفاع عبر شبكة PULSE للجيل الخامس'),title:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_title_002"] ?? 'شكراً لكم'),subtitle:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_subtitle_003"] ?? 'مواقع الجيل الخامس الحيوية عبر شبكة Pulse'),overview:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_overview_004"] ?? 'استكشاف حالات الاستخدام'),restart:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_restart_005"] ?? 'إعادة العرض من البداية'),replay:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_replay_006"] ?? 'إعادة المشهد الختامي'),scene:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_scene_007"] ?? 'بيئة توضيحية للجيل الخامس'),fallback:(globalThis.MOD_AR_TEXT?.["15-closing"]?.["closing_COPY_ar_fallback_008"] ?? 'يبقى المشهد الختامي متاحاً. تعذّر تحميل العرض التفاعلي ثلاثي الأبعاد.')}};
 let state={index:-1,lang:'en',theme:'light',motion:true},builtLang='',renderer=null,model=null,lighting=null,observer=null,registered=false,failed=false,last=0,time=0,frames=0,width=650,height=620,entrance=null;
 const copy=()=>COPY[state.lang],motion=()=>state.motion&&!document.hidden;
 function animateArrival(){entrance?.cancel();entrance=null;if(!motion()||!builtLang)return;entrance=$('.closing-composition').animate?.([{opacity:0,transform:'translateY(24px) scale(.965)'},{opacity:1,transform:'translateY(0) scale(1)'}],{duration:1900,easing:'cubic-bezier(.16,1,.3,1)'})||null}
 function build(){dispose();failed=false;builtLang=state.lang;const c=copy();host.className='closing-slide';host.innerHTML=`<div class="closing-backdrop" aria-hidden="true">${MOD_NIGHT.picture('assets/images/closing-day-v30.webp')}</div><div class="closing-light" aria-hidden="true"></div><div class="closing-composition"><div class="closing-webgl" role="img" aria-label="${c.scene}"></div><span class="closing-scene-caption">${c.scene}</span><p class="closing-fallback" hidden>${c.fallback}</p></div><div class="closing-copy"><p class="eyebrow closing-eyebrow">${c.eyebrow}</p><h1 class="closing-title">${c.title}</h1><p class="closing-subtitle">${c.subtitle}</p><div class="closing-actions"><button type="button" class="closing-overview"><span>${c.overview}</span><i data-lucide="arrow-up-right"></i></button><button type="button" class="closing-restart"><i data-lucide="rotate-ccw"></i><span>${c.restart}</span></button></div></div><button type="button" class="closing-replay" aria-label="${c.replay}" title="${c.replay}"><i data-lucide="rotate-cw"></i><span>${c.replay}</span></button>`;
  /* Copy precedes the scene for reading order and the mobile document flow. */
  host.insertBefore($('.closing-copy'),$('.closing-composition'));
  $('.closing-overview').onclick=()=>window.MOD_SHELL?.goTo('use-cases');$('.closing-restart').onclick=()=>window.MOD_SHELL?.goTo('opening');$('.closing-replay').onclick=()=>replay();
  try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.5));renderer.setClearColor(0,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.07;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.shadowMap.autoUpdate=false;$('.closing-webgl').append(renderer.domElement);const ownedCanvas=renderer.domElement;ownedCanvas.addEventListener('webglcontextlost',e=>{if(renderer?.domElement!==ownedCanvas)return;e.preventDefault();failed=true;$('.closing-fallback').hidden=false;controls();lifecycle()});ownedCanvas.addEventListener('webglcontextrestored',()=>{if(renderer?.domElement===ownedCanvas&&state.index===14){build();requestAnimationFrame(resize)}});
   model=MOD_CLOSING_MODEL.create(state.theme==='dark');model.scene.traverse(o=>{if(o.isDirectionalLight&&o.shadow){o.shadow.mapSize.set(1024,1024);Object.assign(o.shadow.camera,{left:-9,right:9,top:12,bottom:-8,near:1,far:55});o.shadow.camera.updateProjectionMatrix()}});lighting=MOD_NIGHT.lighting(model,draw);lighting.set(state.theme==='dark',false);model.replay(motion());
  }catch(error){failed=true;$('.closing-fallback').hidden=false;console.warn('Closing view fallback:',error)}
  observer=new ResizeObserver(resize);observer.observe($('.closing-composition'));window.lucide?.createIcons({attrs:{'aria-hidden':'true'}});controls();requestAnimationFrame(resize);animateArrival();lifecycle();
 }
 function controls(){if(!builtLang)return;host.classList.toggle('closing-still',!motion());host.classList.toggle('closing-failed',failed);$('.closing-replay').disabled=!state.motion;}
 function resize(){if(!builtLang||state.index!==14)return;const area=$('.closing-webgl');width=area.clientWidth;height=area.clientHeight;if(width<1||height<1)return;renderer?.setSize(width,height,false);draw()}
 function draw(dt=0){if(state.index!==14||failed||!model||!renderer)return;model.update(time,width/Math.max(1,height),typeof dt==='number'?dt:0,motion());renderer.shadowMap.needsUpdate=model.consumeShadowDirty();renderer.render(model.scene,model.camera);frames++}
 function tick(){const now=performance.now(),dt=Math.min(.05,Math.max(0,(now-last)/1000));last=now;time+=dt;draw(dt)}
 function lifecycle(){const run=state.index===14&&motion()&&!failed;if(run&&!registered){last=performance.now();gsap.ticker.add(tick);registered=true}else if(!run&&registered){gsap.ticker.remove(tick);registered=false}}
 function replay(){if(state.index!==14||!builtLang||!state.motion)return;time=0;model?.replay(true);animateArrival();window.MOD_TYPE?.enter?.(state,{replay:true});draw();lifecycle()}
 function dispose(){if(registered)gsap.ticker.remove(tick);registered=false;entrance?.cancel();entrance=null;observer?.disconnect();observer=null;lighting?.dispose();lighting=null;model?.dispose();model=null;if(renderer){const old=renderer;renderer=null;old.dispose();old.forceContextLoss?.()}}
 document.addEventListener('visibilitychange',()=>{if(document.hidden){entrance?.cancel();entrance=null}controls();lifecycle()});
 window.MOD_CLOSING={sync(next){const was=state.index===14,themeChanged=next.theme!==state.theme;state={...next};if(state.index===14){if(!builtLang||builtLang!==state.lang)build();else if(themeChanged)lighting?.set(state.theme==='dark',motion());if(!state.motion){entrance?.cancel();entrance=null}controls();requestAnimationFrame(resize)}else if(was){dispose();builtLang='';host.innerHTML=''}lifecycle()},refresh:()=>draw(),replay,diagnostics:()=>({running:registered,failed,frames,lang:state.lang,theme:state.theme,motion:state.motion,model:model?.diagnostics()})};
})();
