/* Local, deterministic materials and detailed scene construction. */
(()=>{'use strict';const T=THREE;
function create(dark=false){const scene=new T.Scene(),camera=new T.PerspectiveCamera(37,1,.06,240),resources=[],animated=[],images=[];let dead=false,night=dark?1:0;const themeUpdates=[],beacons=[];
const mat=(color,r=.6,m=.15,extra={})=>{const v=new T.MeshPhysicalMaterial({color,roughness:r,metalness:m,...extra});resources.push(v);return v};
const ivory=mat(0xe9e4d8,.49,.12,{clearcoat:.15}),stone=mat(0xffffff,.82,.01),gold=mat(0xb9a275,.3,.78),navy=mat(0x243640,.38,.5,{clearcoat:.4}),glass=mat(0x8bafb9,.13,.22,{clearcoat:1,transparent:true,opacity:.32,depthWrite:false}),leaf=mat(0x65836c,.85,.01),wood=mat(0x9b805f,.68,.02),rubber=mat(0x101e25,.9,.02),led=mat(0xdcecdf,.3,.1,{emissive:0xc6dcc5,emissiveIntensity:1.5});
function canvas(w,h,draw){let c=document.createElement('canvas');c.width=w;c.height=h;draw(c.getContext('2d'),w,h);let tx=new T.CanvasTexture(c);tx.colorSpace=T.SRGBColorSpace;tx.anisotropy=4;resources.push(tx);return tx}
function imageTexture(key,repeat=1,onReady){let tx=new T.Texture();tx.colorSpace=T.SRGBColorSpace;tx.anisotropy=4;tx.wrapS=tx.wrapT=T.RepeatWrapping;tx.repeat.set(repeat,repeat);resources.push(tx);const img=new Image();images.push(img);img.onload=()=>{if(dead)return;tx.image=img;tx.needsUpdate=true;onReady?.(tx);if(typeof requestAnimationFrame==='function')requestAnimationFrame(()=>{if(!dead){window.MOD_CINEMA?.refresh();window.MOD_PTT?.refresh?.();window.MOD_USECASES?.refresh?.();window.MOD_DEPLOYMENT?.refresh?.();window.MOD_IMPLEMENTATION?.refresh?.();window.MOD_CLOSING?.refresh?.();window.MOD_INTRO?.refresh?.()}})};img.src=MOD_CINEMA_ASSETS[key];return tx}
imageTexture('limestone',3,tx=>{stone.map=tx;stone.bumpMap=tx;stone.bumpScale=.025;stone.needsUpdate=true});
const brushed=canvas(256,256,(c,w,h)=>{c.fillStyle='#bfbfbf';c.fillRect(0,0,w,h);for(let i=0;i<600;i++){let v=130+i%90;c.strokeStyle=`rgb(${v},${v},${v})`;c.lineWidth=.3;c.beginPath();c.moveTo(0,(i*43)%256);c.lineTo(256,(i*43)%256);c.stroke()}});brushed.wrapS=brushed.wrapT=T.RepeatWrapping;gold.roughnessMap=brushed;gold.bumpMap=brushed;gold.bumpScale=.003;
let normal=canvas(256,256,(c,w,h)=>{const im=c.createImageData(w,h);for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=(y*w+x)*4;im.data[i]=128+Math.sin(x*.24+y*.11)*18;im.data[i+1]=128+Math.cos(y*.28-x*.05)*20;im.data[i+2]=252;im.data[i+3]=255}c.putImageData(im,0,0)});normal.colorSpace=T.NoColorSpace;normal.wrapS=normal.wrapT=T.RepeatWrapping;
function g(p=scene,x=0,y=0,z=0){const o=new T.Group();o.position.set(x,y,z);p.add(o);return o}function mesh(p,geo,m,x=0,y=0,z=0){const o=new T.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=o.receiveShadow=true;p.add(o);resources.push(geo);return o}function box(p,x,y,z,w,h,d,m=ivory,r=.045){return mesh(p,r?new MOD_THREE_ADDONS.RoundedBoxGeometry(w,h,d,2,Math.min(r,h/3,w/3,d/3)):new T.BoxGeometry(w,h,d),m,x,y,z)}function cyl(p,x,y,z,r,h,m=gold,n=32){return mesh(p,new T.CylinderGeometry(r,r,h,n),m,x,y,z)}function ring(p,x,y,z,r,t=.025,m=gold){let o=mesh(p,new T.TorusGeometry(r,t,8,96),m,x,y,z);o.rotation.x=Math.PI/2;return o}function rod(p,a,b,r=.025,m=gold){let aa=new T.Vector3(...a),bb=new T.Vector3(...b),v=bb.clone().sub(aa),o=cyl(p,...aa.add(bb).multiplyScalar(.5).toArray(),r,v.length(),m,10);o.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),v.normalize());return o}
function label(p,text,x,y,z,w=1.5){const tx=canvas(512,128,c=>{c.fillStyle='#142b36';c.fillRect(0,0,512,128);c.font='500 42px Arial';c.fillStyle='#e6d5ac';c.textAlign='center';c.textBaseline='middle';c.fillText(text,256,64,490)});const m=new T.MeshBasicMaterial({map:tx,toneMapped:false});resources.push(m);return mesh(p,new T.PlaneGeometry(w,w*.25),m,x,y,z)}
function instanced(p,geo,m,poses){const o=new T.InstancedMesh(geo,m,poses.length),d=new T.Object3D();poses.forEach((v,i)=>{d.position.set(...v.p);d.rotation.set(...(v.r||[0,0,0]));d.scale.set(...(v.s||[1,1,1]));d.updateMatrix();o.setMatrixAt(i,d.matrix)});o.castShadow=o.receiveShadow=true;p.add(o);resources.push(geo);return o}
function batchStatic(root,exclude=[]){root.updateMatrixWorld(true);const inv=root.matrixWorld.clone().invert(),groups=new Map();root.traverse(o=>{if(!o.isMesh||o.isInstancedMesh||Array.isArray(o.material))return;for(let a=o;a&&a!==root.parent;a=a.parent)if(exclude.includes(a))return;let key=o.material.uuid+'|'+o.castShadow+'|'+o.receiveShadow;if(!groups.has(key))groups.set(key,[]);groups.get(key).push(o)});for(const list of groups.values()){if(list.length<2)continue;const positions=[],normals=[],uvs=[],n=new T.Vector3(),p=new T.Vector3();for(const o of list){const matrix=inv.clone().multiply(o.matrixWorld),nm=new T.Matrix3().getNormalMatrix(matrix),geo=o.geometry,ix=geo.index,pos=geo.attributes.position,nor=geo.attributes.normal,uv=geo.attributes.uv,count=ix?ix.count:pos.count;for(let j=0;j<count;j++){let i=ix?ix.getX(j):j;p.fromBufferAttribute(pos,i).applyMatrix4(matrix);positions.push(p.x,p.y,p.z);if(nor)n.fromBufferAttribute(nor,i).applyMatrix3(nm).normalize();else n.set(0,1,0);normals.push(n.x,n.y,n.z);uvs.push(uv?uv.getX(i):0,uv?uv.getY(i):0)}o.removeFromParent()}let geo=new T.BufferGeometry();geo.setAttribute('position',new T.Float32BufferAttribute(positions,3));geo.setAttribute('normal',new T.Float32BufferAttribute(normals,3));geo.setAttribute('uv',new T.Float32BufferAttribute(uvs,2));geo.computeBoundingSphere();let m=mesh(root,geo,list[0].material);m.castShadow=list[0].castShadow;m.receiveShadow=list[0].receiveShadow}}
function tree(p,x,z,h=2){let q=g(p,x,0,z);cyl(q,0,.22,0,.65,.44,stone);cyl(q,0,.455,0,.57,.025,rubber);rod(q,[0,.45,0],[.06,h,0],.065,wood);let leaves=[];for(let i=0;i<60;i++){let a=i*2.399,r=.15+(i%7)*.105,y=h-.2+Math.sin(i*.8)*.38;leaves.push({p:[Math.cos(a)*r,y,Math.sin(a)*r],r:[i*.6,a,i*.9],s:[.3,.075,.12]})}instanced(q,new T.IcosahedronGeometry(1,1),leaf,leaves);for(let i=0;i<5;i++)rod(q,[0,h*.6,0],[Math.sin(i*1.3)*.6,h+.1,Math.cos(i*1.3)*.6],.023,wood);return q}
const hemi=new T.HemisphereLight(0xdceeff,0xb9a17d,2.1);scene.add(hemi);let sun=new T.DirectionalLight(0xffe8c0,dark?2.3:3.5);sun.position.set(-9,17,11);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-24,right:24,top:24,bottom:-24,near:1,far:70});sun.shadow.bias=-.00025;sun.shadow.normalBias=.025;scene.add(sun);let fill=new T.DirectionalLight(0xb6d8e9,1.35);fill.position.set(12,5,-10);scene.add(fill);
function beacon(parent,x,y,z,color=0xff493d,size=.035,period=2.5){const material=new T.MeshBasicMaterial({color,toneMapped:false});resources.push(material);const core=mesh(parent,new T.SphereGeometry(size,12,8),material,x,y,z);core.castShadow=false;const tx=canvas(64,64,c=>{let q=c.createRadialGradient(32,32,0,32,32,32);q.addColorStop(0,'rgba(255,255,255,1)');q.addColorStop(.2,'rgba(255,255,255,.5)');q.addColorStop(1,'rgba(255,255,255,0)');c.fillStyle=q;c.fillRect(0,0,64,64)});const sm=new T.SpriteMaterial({map:tx,color,transparent:true,opacity:.3,depthWrite:false,blending:T.AdditiveBlending,toneMapped:false});resources.push(sm);let halo=new T.Sprite(sm);halo.position.set(x,y,z);halo.scale.setScalar(size*8);parent.add(halo);beacons.push({core,halo,period});return core}
function setNight(n){night=n;hemi.intensity=2.1-n*1.12;sun.intensity=3.5-n*2.85;sun.color.set(0xffe8c0).lerp(new T.Color(0x9cbbe3),n);fill.intensity=1.35-n*.45;led.emissiveIntensity=1.5+n*1.1;resources.forEach(m=>{if(m.isMeshStandardMaterial)m.envMapIntensity=1-n*.55});themeUpdates.forEach(f=>f(n))}
// A full-screen, world-oriented photographic sky. Translation cannot expose card edges.
function landscapeBackdrop(day,nightTexture,{coastal=false}={}){
 for(const tx of [day,nightTexture]){tx.wrapS=tx.wrapT=T.ClampToEdgeWrapping;tx.repeat.set(1,1)}
 const hazeDay=new T.Color(coastal?0x9bb9c4:0xc1b195),hazeNight=new T.Color(coastal?0x182d43:0x26394b);
 const uniforms={day:{value:day},nightMap:{value:nightTexture},night:{value:night},inverseProjection:{value:new T.Matrix4()},cameraRotation:{value:new T.Matrix3()},haze:{value:hazeDay.clone()},sky:{value:new T.Color(0x71a4c6)},imageHorizon:{value:coastal?.66:.62}};
 const m=new T.ShaderMaterial({uniforms,depthWrite:false,depthTest:false,fog:false,toneMapped:false,
 vertexShader:'varying vec2 screen;void main(){screen=position.xy;gl_Position=vec4(position.xy,1.,1.);}',
 fragmentShader:`uniform sampler2D day;uniform sampler2D nightMap;uniform float night;uniform float imageHorizon;uniform mat4 inverseProjection;uniform mat3 cameraRotation;uniform vec3 haze;uniform vec3 sky;varying vec2 screen;
 void main(){vec4 ray=inverseProjection*vec4(screen,1.,1.);vec3 d=normalize(cameraRotation*ray.xyz);float elevation=atan(d.y,length(d.xz));float u=.5+atan(d.x,-d.z)/3.3;float v=imageHorizon+elevation;vec2 uv=clamp(vec2(u,v),vec2(.001),vec2(.999));vec3 photo=mix(texture2D(day,uv).rgb,texture2D(nightMap,uv).rgb,night);
 float edges=smoothstep(0.,.16,u)*(1.-smoothstep(.84,1.,u));float vertical=smoothstep(-.12,.06,elevation)*(1.-smoothstep(.91,1.,v));vec3 base=mix(haze,sky,smoothstep(0.,.60,elevation));gl_FragColor=vec4(mix(base,photo,edges*vertical),1.);
 #include <colorspace_fragment>
 }`});resources.push(m);
 const q=mesh(scene,new T.PlaneGeometry(2,2),m);q.name='continuous-landscape';q.castShadow=q.receiveShadow=false;q.frustumCulled=false;q.renderOrder=-1000;
 q.onBeforeRender=(_r,_s,cam)=>{uniforms.inverseProjection.value.copy(cam.projectionMatrixInverse);uniforms.cameraRotation.value.setFromMatrix4(cam.matrixWorld)};
 themeUpdates.push(n=>{uniforms.night.value=n;uniforms.haze.value.copy(hazeDay).lerp(hazeNight,n);uniforms.sky.value.set(0x71a4c6).lerp(new T.Color(0x071423),n)});
 return q;
}
function horizon(key='coastal-horizon'){let tx=imageTexture(key,1),m=new T.MeshBasicMaterial({map:tx,side:T.BackSide,fog:false,depthWrite:false,depthTest:false});resources.push(m);let sky=mesh(scene,new T.CylinderGeometry(105,105,62,128,1,true),m,0,11,0);sky.rotation.y=1.6;sky.castShadow=sky.receiveShadow=false;sky.renderOrder=-100;let nm=new T.MeshBasicMaterial({map:imageTexture(key+'-night',1),side:T.BackSide,fog:false,transparent:true,opacity:night,depthWrite:false,depthTest:true});resources.push(nm);let skyNight=mesh(scene,sky.geometry,nm,0,11,0);skyNight.rotation.y=1.6;skyNight.castShadow=skyNight.receiveShadow=false;skyNight.renderOrder=-99;themeUpdates.push(n=>nm.opacity=n);return sky}
setNight(night);return {scene,camera,setNight,beacon,themeUpdates,batchStatic,mat,g,mesh,box,cyl,ring,rod,label,instanced,tree,canvas,imageTexture,horizon,landscapeBackdrop,resources,normal,stone,ivory,gold,navy,glass,leaf,wood,rubber,led,animated,animate(t){animated.forEach(f=>f(t));beacons.forEach((b,i)=>{let pulse=Math.pow(Math.max(0,Math.sin((t/b.period+i*.13)*Math.PI*2)),12);b.halo.material.opacity=.06+pulse*(.28+night*.38);b.core.material.color.setScalar(.24+pulse*.76).multiply(new T.Color(b.halo.material.color))})},dispose(){dead=true;images.forEach(i=>i.onload=null);new Set(resources).forEach(r=>r.dispose?.())}}}
function coast(k){const {scene,box,cyl,ring,g,mesh,mat,stone,ivory,gold,navy,glass,wood,rod,instanced,led}=k;k.horizon();
let water=mat(0x3b8895,.22,.45,{clearcoat:1,clearcoatRoughness:.12,normalMap:k.normal,normalScale:new T.Vector2(.4,.4)});k.normal.repeat.set(22,22);k.themeUpdates.push(n=>water.color.set(0x3b8895).lerp(new T.Color(0x183446),n));let sea=mesh(scene,new T.PlaneGeometry(200,200,80,80),water,0,-.65,0);sea.rotation.x=-Math.PI/2;sea.castShadow=false;const pos=sea.geometry.attributes.position,orig=new Float32Array(pos.array);k.animated.push(t=>{for(let i=0;i<pos.count;i++)pos.setZ(i,Math.sin(orig[i*3]*.55+t*.7)*.048+Math.cos(orig[i*3+1]*.7+t*.55)*.04);pos.needsUpdate=true;sea.geometry.computeVertexNormals();k.normal.offset.set(t*.004,t*.002)});
let shape=new T.Shape();const outline=[[-13,5],[-12,-1],[-9,-5],[-3,-6],[2,-5],[5,-3],[9,-1],[9,4],[5,6],[-2,7],[-9,7]];outline.forEach(([x,z],i)=>i?shape.lineTo(x,-z):shape.moveTo(x,-z));shape.closePath();let land=mesh(scene,new T.ExtrudeGeometry(shape,{depth:.8,bevelEnabled:true,bevelSegments:2,steps:1,bevelSize:.2,bevelThickness:.15}),stone,0,-.9,0);land.rotation.x=-Math.PI/2;
let rocks=[];for(let i=0;i<120;i++){const j=i%outline.length,a=outline[j],b=outline[(j+1)%outline.length],f=(i/outline.length)%1;rocks.push({p:[T.MathUtils.lerp(a[0],b[0],f),-.32,T.MathUtils.lerp(a[1],b[1],f)],r:[i*.5,i*.8,i*.13],s:[.45+(i%4)*.13,.28+(i%3)*.14,.42]})}instanced(scene,new T.DodecahedronGeometry(1,1),stone,rocks);
// Pavilion with real glazing, columns, interior desks, deck joints and louver canopy.
const pavilion=g(scene,-1.8,.1,-2.6);box(pavilion,0,.08,0,5.6,.16,3.7,stone);for(let x of [-2.6,2.6])for(let z of [-1.6,1.6])box(pavilion,x,1.13,z,.18,2.1,.18,gold);for(let x=-2.4;x<2.6;x+=.8){box(pavilion,x,1.08,-1.59,.74,1.9,.035,glass);box(pavilion,x+.39,1.1,-1.58,.035,2,.06,gold)}for(let z=-1.2;z<=1.2;z+=.8)box(pavilion,-2.58,1.08,z,.035,1.9,.74,glass);box(pavilion,0,2.3,0,6.2,.2,4.2,ivory);for(let x=-2.8;x<=2.8;x+=.22)box(pavilion,x,2.14,.1,.065,.12,3.9,wood);box(pavilion,0,2.065,1.85,5.8,.026,.028,led);for(let x of [-1.4,1.4]){box(pavilion,x,.82,-.6,1.4,.08,.75,wood);box(pavilion,x,1.15,-.85,.7,.45,.06,navy);box(pavilion,x,.4,-.6,.08,.8,.08,gold);box(pavilion,x,.48,.4,.48,.08,.5,navy);box(pavilion,x,.8,.64,.48,.6,.07,navy)}
for(let i=0;i<3;i++)box(scene,-1.8,.12-i*.055,-.36+i*.22,5.5,.1,.26,stone);
for(let x=-10;x<8;x+=1.2)for(let z=-.1;z<5;z+=1.2)box(scene,x,.14,z,1.18,.016,1.18,ivory,0);
// Jetty with rails, fenders, ladders and dock hardware.
box(scene,6,.16,-6.3,2.5,.24,9,stone);for(let i=0;i<37;i++)box(scene,6,.31,-10.7+i*.24,2.45,.07,.2,wood,.008);for(let z=-10.3;z<-2;z+=1.1)for(let x of [4.86,7.14]){cyl(scene,x,.84,z,.027,1,gold,12);for(let y of [.58,1.12,1.32])rod(scene,[x,y,z],[x,y,z+1.1],.019,gold)}for(let z of [-9.4,-6.8,-4.2]){for(let x of [4.7,7.3]){cyl(scene,x,.35,z,.09,.3,navy);ring(scene,x,.12,z,.21,.08,k.rubber).rotation.x=0}}for(let z of [-8.8,-6.7]){for(let x of [7.4,7.85])rod(scene,[x,.65,z],[x,-.6,z],.035,gold);for(let y=-.5;y<.6;y+=.22)rod(scene,[7.4,y,z],[7.85,y,z],.024,gold)}
const beacon=g(scene,7,0,2);cyl(beacon,0,1.8,0,.36,3.6,ivory);for(let y=.2;y<3.6;y+=.28)ring(beacon,0,y,0,.366,.007,gold);cyl(beacon,0,3.65,0,.78,.18,gold);cyl(beacon,0,4.02,0,.6,.65,glass);cyl(beacon,0,4.42,0,.84,.12,ivory);for(let a=0;a<Math.PI*2;a+=Math.PI/4){cyl(beacon,Math.sin(a)*.62,4.02,Math.cos(a)*.62,.025,.69,gold,10)}let lamp=cyl(beacon,0,4.02,0,.15,.38,led);ring(beacon,0,3.83,0,.95,.035,gold);for(let a=0;a<6.2;a+=.8)rod(beacon,[Math.sin(a)*.95,3.4,Math.cos(a)*.95],[Math.sin(a)*.95,3.84,Math.cos(a)*.95],.025,gold);
for(let i=0;i<4;i++){let a=g(scene,1+i*1.1,.7,4.6);let panel=box(a,0,0,0,.9,.08,1.45,navy);panel.rotation.x=-.28;for(let j=0;j<5;j++)box(a,0,.045,-.58+j*.28,.84,.008,.014,gold,0);cyl(a,0,-.3,0,.04,.6,gold)}
for(let [x,z] of [[-9,-2],[-6,-3.7],[2,-3.5],[8,3.6]])k.tree(scene,x,z,1.6);
for(let [x,z] of [[-5,5.2],[-2,5.5],[4,-1]]){cyl(scene,x,.4,z,.08,.8,navy);cyl(scene,x,.82,z,.092,.1,led)}
k.beacon(beacon,0,4.53,0,0xffb85d,.035,3.1);const siteLabel=k.label(scene,'COASTAL OBSERVATION',-1.8,1.88,-.87,2.3);
k.batchStatic(scene,[sea]);return {sea,pavilion,beacon,siteLabel};}
window.MOD_PREMIUM_KIT={create,coast};})();
