/* Slide 03: five independently modelled security narratives. All copy is external. */
(()=>{'use strict';
const host=document.getElementById('securitySlide'),icons=['key-round','shield-check','scan-line','lock-keyhole','network'],artNames=['pam','firewall','siem','keys','identity'];
let state={index:-1,lang:'en',theme:'light',motion:true},selected=0,built=false,renderer,scene,camera,visual,models=[],shackle,scan,identity=[],packets=[],bars=[],statusLEDs=[],ring,sequence,shotTween,registered=false,last=0,frames=0;
const timer={elapsed:0},clock={t:0,night:0},shot={x:5,y:3.6,z:9};
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const txt=()=>MOD_COPY[state.lang].security;
function build(){const t=txt();if(!built){host.innerHTML=`<div class="security-background" aria-hidden="true"><span class="paired day" style="background-image:url('assets/images/security-room.webp')"></span><span class="paired night" style="background-image:url('assets/images/security-room.webp')"></span></div><header class="security-heading"><p class="eyebrow"></p><h1></h1><p class="security-subtitle"></p><button class="security-replay"><i data-lucide="rotate-ccw"></i><span></span></button></header><div class="security-main"><div class="security-visual"><canvas class="security-canvas" aria-hidden="true"></canvas><span class="security-orbit-label"></span><div class="security-visual-label"><strong></strong><small></small></div></div><article class="security-detail" aria-live="polite"></article></div><div class="security-tabs" role="group"></div>`;visual=host.querySelector('.security-visual');host.querySelector('.security-replay').onclick=replay;built=true;init3D()}
host.setAttribute('aria-label',t.title);host.querySelector('.eyebrow').textContent=t.eyebrow;host.querySelector('h1').textContent=t.title;host.querySelector('.security-subtitle').textContent=t.subtitle;host.querySelector('.security-replay span').textContent=t.replay;host.querySelector('.security-replay').setAttribute('aria-label',t.replay);host.querySelector('.security-visual-label strong').textContent=t.core;host.querySelector('.security-visual-label small').textContent=t.concept;
const tabs=host.querySelector('.security-tabs');tabs.setAttribute('aria-label',t.select);tabs.innerHTML=t.items.map((p,i)=>`<button class="security-tab" data-security="${i}" aria-pressed="false"><span class="security-card-art" aria-hidden="true"><span class="paired day" style="background-image:url('assets/images/security-${artNames[i]}.webp')"></span><span class="paired night" style="background-image:url('assets/images/security-${artNames[i]}.webp')"></span><span class="security-card-shade"></span><span class="security-card-icon"><i data-lucide="${icons[i]}"></i></span><span class="security-card-number" dir="ltr">0${i+1}</span></span><span class="security-card-copy"><strong>${esc(p.name)}</strong><small>${esc(p.short)}</small></span></button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{sequence?.kill();sequence=null;host.style.setProperty('--security-progress','100%');select(+b.dataset.security,true)});select(selected,false);}
function detail(){const t=txt(),p=t.items[selected];host.querySelector('.security-orbit-label').innerHTML='<bdi dir="ltr">'+String(selected+1).padStart(2,'0')+' / 05</bdi><span>'+esc(p.short)+'</span>';host.querySelector('.security-detail').innerHTML=`<div class="security-detail-top"><span class="security-emblem"><i data-lucide="${icons[selected]}"></i></span><div><small>${esc(p.name)}</small><p>${esc(p.subtitle)}</p></div></div><h2>${esc(p.headline)}</h2><ul class="security-points">${p.points.map(s=>`<li><i data-lucide="check"></i><span>${esc(s)}</span></li>`).join('')}</ul><div class="security-scope" aria-label="${esc(t.scope)}">${p.scope.map(s=>`<span>${esc(s)}</span>`).join('')}</div><div class="security-flow">${p.flow.map((s,i)=>(i?'<i data-lucide="chevron-right"></i>':'')+'<span>'+esc(s)+'</span>').join('')}</div>`;host.querySelectorAll('[data-security]').forEach((b,i)=>{b.classList.toggle('active',i===selected);b.setAttribute('aria-pressed',String(i===selected))});lucide.createIcons({attrs:{'aria-hidden':'true'}})}
function select(i,animate=true){selected=Math.max(0,Math.min(4,i));i=selected;detail();const duration=animate&&state.motion?1.25:0;models.forEach((g,n)=>{gsap.killTweensOf(g.scale);gsap.to(g.scale,{x:n===i?1:.001,y:n===i?1:.001,z:n===i?1:.001,duration,ease:'power3.inOut',onUpdate:()=>{if(!registered)draw(true)}})});shotTween?.kill();const shots=[[4,3.1,9],[5.3,3.8,9],[-4.2,4.8,9],[3.7,3.3,8.7],[-3.8,4.8,9.2]];const q=shots[i];shotTween=gsap.to(shot,{x:q[0],y:q[1],z:q[2],duration:duration*1.4,ease:'power2.inOut',onUpdate:()=>{if(!registered)draw(true)}});if(duration)gsap.fromTo(host.querySelector('.security-detail'),{opacity:.15,y:12},{opacity:1,y:0,duration:.6,overwrite:true});draw(true)}
function replay(){sequence?.kill();timer.elapsed=0;select(0,true);sequence=gsap.to(timer,{elapsed:5,duration:MOD_CONFIG.security.layerSeconds*5,ease:'none',onUpdate(){const i=Math.min(4,Math.floor(timer.elapsed));if(i!==selected)select(i,true);host.style.setProperty('--security-progress',((timer.elapsed%1)*100)+'%')},onComplete(){host.style.setProperty('--security-progress','100%')}});lifecycle()}
function init3D(){const T=THREE;try{renderer=new T.WebGLRenderer({canvas:host.querySelector('canvas'),antialias:true,alpha:true,powerPreference:'high-performance'})}catch{return}renderer.setPixelRatio(Math.min(devicePixelRatio||1,MOD_CONFIG.security.maxPixelRatio));renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;
scene=new T.Scene();camera=new T.PerspectiveCamera(32,1,.1,70);const studio=new MOD_THREE_ADDONS.RoomEnvironment(renderer),pm=new T.PMREMGenerator(renderer);scene.environment=pm.fromScene(studio,.04).texture;studio.dispose();pm.dispose();scene.add(new T.HemisphereLight(0xfff7e6,0x26364a,1.45));const key=new T.DirectionalLight(0xffdfad,3.4);key.position.set(-3,8,7);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.normalBias=.035;scene.add(key);const rim=new T.DirectionalLight(0xb8d3ff,2.7);rim.position.set(6,4,-4);scene.add(rim);
const gold=new T.MeshStandardMaterial({color:0xb99454,metalness:.88,roughness:.24}),ivory=new T.MeshStandardMaterial({color:0xf0e7d3,metalness:.25,roughness:.28}),navy=new T.MeshStandardMaterial({color:0x182b36,metalness:.65,roughness:.26}),glow=new T.MeshStandardMaterial({color:0xffd899,emissive:0xe2aa48,emissiveIntensity:1.2,metalness:.3,roughness:.3}),green=new T.MeshStandardMaterial({color:0x8adac4,emissive:0x51ac92,emissiveIntensity:.5}),red=new T.MeshStandardMaterial({color:0xdb8265,emissive:0xa33422,emissiveIntensity:.6});
const mesh=(g,geo,mat,x=0,y=0,z=0)=>{const m=new T.Mesh(geo,mat);m.position.set(x,y,z);m.castShadow=true;m.receiveShadow=true;g.add(m);return m};const box=(g,w,h,d,mat,x=0,y=0,z=0)=>mesh(g,new MOD_THREE_ADDONS.RoundedBoxGeometry(w,h,d,3,.06),mat,x,y,z);const cyl=(g,r,h,mat,x=0,y=0,z=0)=>mesh(g,new T.CylinderGeometry(r,r,h,64),mat,x,y,z);const orb=(g,r,mat,x,y,z)=>mesh(g,new T.SphereGeometry(r,24,16),mat,x,y,z);const bar=(g,a,b,r,mat)=>{const av=new T.Vector3(...a),bv=new T.Vector3(...b),m=mesh(g,new T.CylinderGeometry(r,r,av.distanceTo(bv),12),mat);m.position.copy(av).add(bv).multiplyScalar(.5);m.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),bv.sub(av).normalize());return m};
const base=new T.Group();scene.add(base);cyl(base,2.65,.2,navy,0,-.75,0);cyl(base,2.7,.055,gold,0,-.62,0);cyl(base,2.49,.04,navy,0,-.58,0);ring=mesh(base,new T.TorusGeometry(2.6,.025,8,128),glow,0,-.53,0);ring.rotation.x=Math.PI/2;for(let i=0;i<48;i++){const a=i*Math.PI/24;const mark=box(base,.023,.012,i%4===0?.18:.08,gold,Math.sin(a)*2.35,-.548,Math.cos(a)*2.35);mark.rotation.y=a}
for(let i=0;i<5;i++){const g=new T.Group();scene.add(g);g.scale.setScalar(.001);models.push(g)}
// PAM: an engineered lock with an articulated shackle, keyhole and access tokens.
const pam=models[0];box(pam,2.05,1.45,.68,ivory,0,.6,0);box(pam,1.83,1.22,.04,navy,0,.6,.36);box(pam,.1,.31,.04,gold,0,.45,.405);orb(pam,.14,gold,0,.68,.42);shackle=new T.Group();shackle.position.y=1.15;pam.add(shackle);const curve=new T.CatmullRomCurve3([new T.Vector3(-.68,0,0),new T.Vector3(-.68,.82,0),new T.Vector3(0,1.23,0),new T.Vector3(.68,.82,0),new T.Vector3(.68,0,0)]);mesh(shackle,new T.TubeGeometry(curve,64,.115,16,false),gold);for(let i=0;i<3;i++){const token=box(pam,.46,.62,.09,navy,-1.65+i*.35,-.02,.6+i*.16);token.rotation.y=-.3;orb(pam,.07,glow,-1.65+i*.35,.1,.66+i*.16)}
// Firewall: masonry-like physical perimeter with a visible central gateway.
const fw=models[1];for(let y=0;y<4;y++)for(let x=0;x<5;x++){if(x===2&&y<3)continue;box(fw,.63,.39,.43,y===3?gold:ivory,(x-2)*.69,-.32+y*.45,0)}box(fw,.52,1.33,.10,navy,0,.17,.1);for(let y=0;y<5;y++)box(fw,.37,.025,.03,glow,0,-.30+y*.23,.165);
// SIEM: three detailed rack towers, log channels and a sweeping scan plane.
const siem=models[2];for(let i=0;i<3;i++){const x=(i-1)*1.18;box(siem,.88,2,.72,navy,x,.46,0);for(let j=0;j<6;j++){box(siem,.72,.22,.045,ivory,x,-.28+j*.29,.385);for(let k=0;k<3;k++){let lm=green.clone();const l=orb(siem,.022,lm,x-.26+k*.09,-.28+j*.29,.419);statusLEDs.push(l)}}for(let j=0;j<4;j++){const b=box(siem,.15,.4+j*.15,.15,gold,x-.32+j*.21,-.35,-.8);bars.push(b)}}scan=mesh(siem,new T.PlaneGeometry(3.8,1.4),new T.MeshBasicMaterial({color:0xe8c786,transparent:true,opacity:.18,side:T.DoubleSide,depthWrite:false}),0,.8,.5);scan.rotation.x=-Math.PI/2;
// Key management: machined key suspended over nested transport rings.
const keys=models[3];const keyGroup=new T.Group();keys.add(keyGroup);keyGroup.rotation.z=-.6;keyGroup.position.set(-.25,1.1,0);mesh(keyGroup,new T.TorusGeometry(.57,.15,16,64),gold,0,.55,0);box(keyGroup,.28,1.52,.25,gold,0,-.54,0);box(keyGroup,.55,.23,.25,gold,.2,-1.09,0);box(keyGroup,.47,.23,.25,gold,.17,-.69,0);for(let j=0;j<3;j++){const r=mesh(keys,new T.TorusGeometry(1.45+j*.31,.033,10,96),j===1?glow:gold,0,-.30+j*.12,0);r.rotation.x=Math.PI/2;r.rotation.z=j*.4}
// Identity: central authority, three linked user/device/policy nodes.
const ad=models[4];box(ad,.9,1.65,.65,ivory,0,.7,-.55);box(ad,.72,1.37,.04,navy,0,.7,-.205);for(let i=0;i<5;i++)box(ad,.48,.04,.035,glow,0,.2+i*.23,-.175);for(let i=0;i<3;i++){const a=(i-1)*1.2,x=Math.sin(a)*1.75,z=Math.cos(a)*1.3;const n=new T.Group();n.position.set(x,0,z);ad.add(n);cyl(n,.38,.1,gold,0,-.39,0);if(i===0){orb(n,.19,ivory,0,.42,0);mesh(n,new T.CylinderGeometry(.14,.3,.46,24),navy,0,.0,0)}else if(i===1){box(n,.65,.46,.09,navy,0,.26,0);box(n,.54,.33,.025,glow,0,.26,.06);bar(n,[0,-.3,0],[0,.05,0],.04,gold)}else{box(n,.48,.69,.1,ivory,0,.22,0);for(let j=0;j<3;j++)box(n,.28,.025,.03,gold,0,.08+j*.13,.07)}bar(ad,[0,-.32,-.55],[x,-.32,z],.022,gold);identity.push(n)}
for(let i=0;i<22;i++){const p=orb(scene,.055,i%5===0?red:green,0,0,0);packets.push(p)}
new ResizeObserver(resize).observe(visual);resize();}
function resize(){if(!renderer||!visual.clientWidth||!visual.clientHeight)return;const cv=host.querySelector("canvas"),w=cv.clientWidth,h=cv.clientHeight;if(!w||!h)return;renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix();draw(true)}
function draw(force=false){if(!renderer||state.index!==2)return;const now=performance.now();if(!force&&now-last<1000/30)return;last=now;const t=clock.t;camera.position.set(shot.x+Math.sin(t*.12)*.2,shot.y,shot.z);camera.lookAt(0,.55,0);camera.updateMatrixWorld();renderer.toneMappingExposure=1.02-clock.night*.18;
statusLEDs.forEach((l,i)=>l.material.emissiveIntensity=.25+Math.pow(Math.max(0,Math.sin(t*1.8+i*.45)),6)*.85);if(shackle){shackle.position.y=1.15+Math.pow(Math.max(0,Math.sin(t*.65)),2)*.28;shackle.rotation.y=Math.max(0,Math.sin(t*.65))*.12}if(scan)scan.position.y=.45+Math.sin(t*.9)*.75;bars.forEach((b,i)=>b.scale.y=.8+Math.sin(t*1.3+i)*.3);if(models[3])models[3].rotation.y=Math.sin(t*.25)*.33;identity.forEach((n,i)=>n.position.y=Math.sin(t*.8+i)*.025);if(ring)ring.material.emissiveIntensity=.7+Math.sin(t*1.2)*.3;
packets.forEach((p,i)=>{const q=(t*.14+i/22)%1;p.visible=true;if(selected===1){const denied=i%5===0;p.position.set(denied?-2.8+Math.sin(q*Math.PI)*2.35:-3+q*6,.16+(i%4)*.25,.5);p.scale.setScalar(denied?.9:1)}else if(selected===2){p.position.set((i%3-1)*1.18,-.3+q*2.3,.46);p.scale.setScalar(.65)}else if(selected===4){const j=i%3,a=(j-1)*1.2;p.position.set(Math.sin(a)*1.75*q,-.28,-.55+(Math.cos(a)*1.3+.55)*q);p.scale.setScalar(.8)}else{const a=q*Math.PI*2;p.position.set(Math.cos(a)*2.06,-.22+Math.sin(a*2)*.11,Math.sin(a)*2.06);p.scale.setScalar(.7)}});models.forEach(g=>g.visible=g.scale.x>.008);renderer.render(scene,camera);frames++;}
function tick(_,delta){clock.t+=Math.min(delta||16,60)/1000;draw()}
function lifecycle(){const run=state.index===2&&state.motion&&!document.hidden;host.classList.toggle('security-paused',!run);if(run&&!registered){gsap.ticker.add(tick);registered=true}else if(!run&&registered){gsap.ticker.remove(tick);registered=false}if(run){sequence?.resume();shotTween?.resume()}else{sequence?.pause();shotTween?.pause()}models.forEach(g=>gsap.getTweensOf(g.scale).forEach(t=>run?t.resume():t.pause()));}
window.MOD_SECURITY={sync(s){const entered=s.index===2&&state.index!==2,language=s.lang!==state.lang,theme=s.theme!==state.theme;state={...s};if(s.index===2){if(!built||language)build();if(entered){resize();replay();if(state.motion)gsap.fromTo(host.querySelectorAll(".security-tab"),{opacity:0,y:22},{opacity:1,y:0,duration:.75,stagger:.08,ease:"power3.out",clearProps:"transform,opacity"})}if(theme||entered)gsap.to(clock,{night:s.theme==='dark'?1:0,duration:s.motion?1:0,onUpdate:()=>draw(true)});requestAnimationFrame(resize)}lifecycle()},select:i=>{sequence?.kill();sequence=null;select(i,true)},replay,diagnostics:()=>({available:!!renderer,selected,frames,time:clock.t,running:registered,camera:{x:shot.x,y:shot.y,z:shot.z},models:models.map(g=>({visible:g.visible,scale:g.scale.x})),calls:renderer?.info.render.calls})};document.addEventListener('visibilitychange',lifecycle);
})();
